import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Multi-sidebar layout
 *  - docsSidebar         → "Docs" navbar item          (intro, guide/)
 *  - architectureSidebar → "Architecture" navbar item
 *  - contributeSidebar   → "Open Source" navbar item
 *  - releaseNotesSidebar → "Release Notes" navbar item
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: '가이드',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'guide'}],
    },
  ],

  architectureSidebar: [
    {type: 'autogenerated', dirName: 'architecture'},
  ],

  contributeSidebar: [
    {type: 'autogenerated', dirName: 'contribute'},
  ],

  releaseNotesSidebar: [
    {type: 'autogenerated', dirName: 'release-notes'},
  ],
};

export default sidebars;
