import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Multi-sidebar layout
 *  - docsSidebar         → "Docs" navbar item          (intro, guide/)
 *  - architectureSidebar → "Architecture" navbar item
 *  - contributeSidebar   → "Open Source" navbar item
 *  - releaseNotesSidebar → "Release Notes" navbar item
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'guide/intro',
    {
      type: 'category',
      label: '가이드',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'guide'}],
    },
  ],

  aboutSidebar: [
    {
      type: 'category',
      label: '프로젝트 소개',
      link: {type: 'generated-index', slug: '/about'},
      items: [{type: 'autogenerated', dirName: 'about'}],
    },
  ],

  architectureSidebar: [
    {
      type: 'category',
      label: '아키텍처',
      link: {type: 'generated-index', slug: '/architecture'},
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
  ],

  installSidebar: [
    {type: 'autogenerated', dirName: 'install'},
  ],

  pocSidebar: [
    {type: 'autogenerated', dirName: 'poc'},
  ],

  blogSidebar: [
    {
      type: 'category',
      label: '블로그',
      link: {type: 'generated-index', slug: '/blog'},
      items: [{type: 'autogenerated', dirName: 'blog'}],
    },
  ],

  contributeSidebar: [
    {type: 'autogenerated', dirName: 'contribute'},
  ],

  releaseNotesSidebar: [
    {
      type: 'category',
      label: '릴리즈 노트',
      link: {type: 'generated-index', slug: '/release-notes'},
      items: [{type: 'autogenerated', dirName: 'release-notes'}],
    },
  ],
};

export default sidebars;
