import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Multi-sidebar layout
 *  - docsSidebar         → "Docs" navbar item       (intro, guide/, plus tutorial samples for now)
 *  - architectureSidebar → "Architecture" navbar item
 *  - contributeSidebar   → "Open Source" navbar item
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: '가이드',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'guide'}],
    },
    {
      type: 'category',
      label: '튜토리얼 (샘플 — 추후 제거)',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'tutorial-basics'},
        {type: 'autogenerated', dirName: 'tutorial-extras'},
      ],
    },
  ],

  architectureSidebar: [
    {type: 'autogenerated', dirName: 'architecture'},
  ],

  contributeSidebar: [
    {type: 'autogenerated', dirName: 'contribute'},
  ],
};

export default sidebars;
